import type { Guide } from "./guides";

/**
 * Kahve rehberi — ikinci seri (Ekim 2026). Bilgi amaçlı aramalara yönelik özgün içerik:
 * single origin, filtre kahve, V60 reçeteleri, toptan alım, barista, kahve tarihi, Eskişehir...
 */
export const MORE_GUIDES: Guide[] = [
  {
    slug: "single-origin-kahve-nedir",
    title: "Single Origin Kahve Nedir? Tek Köken ile Harman Arasındaki Fark",
    description:
      "Single origin (tek köken) kahve ne demek, harman (blend) kahveden farkı ne, hangisini seçmeli? Ülke, bölge, çiftlik ve lot kavramlarıyla tek köken kahveyi anlatıyoruz.",
    image: "/photos/cherries-branch.webp",
    date: "2026-10-09",
    readMin: 5,
    blocks: [
      { p: "Bir paketin üzerinde “Etiyopya · Sidamo” ya da “Endonezya · Garut, Batı Java” yazıyorsa, elinizde tek köken bir kahve vardır. Single origin, Türkçesiyle tek köken; çekirdeklerin tamamının tek bir ülkeden, çoğu zaman tek bir bölgeden, hatta tek bir çiftlik ya da kooperatiften geldiğini anlatır." },
      { h2: "Tek köken neden önemli?" },
      { p: "Kahve, yetiştiği yerin izini taşıyan bir meyvenin çekirdeğidir. Toprak, rakım, iklim, bitki çeşidi ve işleme yöntemi fincandaki tadı doğrudan belirler. Tek köken bir kahve bu “terroir”u saklamadan, en saf hâliyle gösterir: Bir Etiyopya kahvesinde çiçeksi ve meyvemsi notalar, bir Java kahvesinde baharat ve gövde öne çıkar." },
      { h2: "Ülke, bölge, çiftlik, lot" },
      { ul: [
        "Ülke: En geniş tanım. “Kolombiya” yazan bir paket hâlâ çok farklı bölgelerden gelen çekirdekleri içerebilir.",
        "Bölge: Sidamo, Huila, Batı Java gibi. Tat profili daha öngörülebilir hâle gelir.",
        "Çiftlik / istasyon: Tek bir üreticinin ya da yıkama istasyonunun kahvesi. İzlenebilirlik en üst seviyededir.",
        "Lot / mikrolot: Aynı çiftlikte belirli bir parsel, çeşit ya da işleme denemesinden çıkan küçük parti. Sınırlı ve çoğu zaman en ilginç fincanlar buradan çıkar.",
      ] },
      { h2: "Harman (blend) kahve nedir?" },
      { p: "Harman, farklı kökenlerden gelen çekirdeklerin belirli bir tat hedefi için birleştirilmesidir. İyi bir harman kötü bir kahveyi saklamak için değil, dengeyi kurmak için yapılır: Bir kökenin meyvesini diğerinin gövdesiyle tamamlamak, sütle uyumlu ve her gün aynı lezzeti veren bir espresso tabanı oluşturmak gibi. Pagi ve Tanah harmanlarımız bu yaklaşımla, Etiyopya'nın meyvesini Endonezya'nın gövdesiyle buluşturur." },
      { h2: "Hangisini seçmeliyim?" },
      { p: "Filtre kahve, V60 ya da AeroPress ile demliyor ve fincanda kökenin karakterini aramak istiyorsanız tek köken kahve iyi bir başlangıçtır. Sütlü içecekler ve her gün aynı tutarlılıkta bir espresso istiyorsanız harmanlar daha bağışlayıcıdır. Kararsızsanız: Orta kavrulmuş, tatlılığı yüksek bir tek köken — örneğin çikolata, orman meyveleri ve tarçın notalı Manis (Etiyopya · Sidamo) — hem filtrede hem Türk kahvesinde rahatça içilir." },
      { h2: "Tek köken kahvede etikette ne aramalı?" },
      { ul: ["Köken bilgisi: ülke + bölge (mümkünse çiftlik)", "İşleme yöntemi: washed, natural, honey, anaerobik", "Kavrum tarihi (son kullanma tarihi değil)", "Tat notaları ve önerilen demleme yöntemi"] },
      { links: [{ href: "/kategori/single-origin", label: "Single origin kahvelerimiz" }, { href: "/kahveler/manis-blend-espresso-filtre", label: "Manis Etiyopya Sidamo" }, { href: "/rehber/nitelikli-kahve-nasil-secilir", label: "Nitelikli kahve nasıl seçilir?" }] },
    ],
  },
  {
    slug: "eskisehir-kahve-kulturu",
    title: "Eskişehir'de Kahve Kültürü: Türk Kahvesinden 3. Nesil Kahveye",
    description:
      "Eskişehir'in kahve geleneği ve değişen kahve kültürü: Odunpazarı'nın Türk kahvesinden öğrenci şehrinin specialty kahve dükkânlarına, şehirde taze kavrum kahve nereden alınır?",
    image: "/photos/coffee-bar-jars.webp",
    date: "2026-10-09",
    readMin: 4,
    blocks: [
      { p: "Eskişehir'de kahve hep bir buluşma bahanesi oldu. Odunpazarı'nın cumbalı evleri arasında ikram edilen Türk kahvesinden Porsuk kıyısındaki kafelere, şehrin ritmi fincanların etrafında kurulur. Bugün ise bu geleneğe yeni bir sayfa ekleniyor: kökeni bilinen, taze kavrulan 3. nesil kahve." },
      { h2: "Türk kahvesi: misafirliğin dili" },
      { p: "Türk kahvesi ve kültürü 2013'te UNESCO İnsanlığın Somut Olmayan Kültürel Mirası listesine alındı. Eskişehir'de de kahve, misafire yapılan ilk ikram, söz kesiminin, uzun sohbetlerin ve “bir kahvenin kırk yıl hatırı”nın simgesi. Bu gelenek, yeni nesil kahvenin de temelini oluşturuyor: İyi kahve, paylaşılınca güzeldir." },
      { h2: "Öğrenci şehrinden specialty kahve şehrine" },
      { p: "Üç üniversitesi ve genç nüfusuyla Eskişehir, yeni tatları deneme konusunda Türkiye'nin en açık şehirlerinden biri. V60, Chemex ve AeroPress gibi elle demleme yöntemleri, Etiyopya ya da Endonezya gibi kökenlerin tadına odaklanan menüler şehirde hızla yaygınlaştı. Artık birçok kişi evinde kendi kahvesini demliyor ve taze kavrulmuş çekirdek arıyor." },
      { h2: "Eskişehir'de kavrulan kahve" },
      { p: "Flores Roastery olarak Tepebaşı'ndaki atölyemizde kahveyi her hafta küçük partiler hâlinde kavuruyoruz. Endonezya'dan doğrudan ticaretle gelen Ruso Exotics serisi, Etiyopya Sidamo'dan Manis ve Kolombiya, El Salvador ve Meksika'nın tek köken kahveleri, Eskişehir içinde kendi kuryemizle aynı gün kapınıza geliyor. Coffee Bar'ımızda ise kahveleri satın almadan önce tadabilirsiniz." },
      { h2: "Eskişehir'de kahve keyfi için öneriler" },
      { ul: [
        "Taze kavrum tarihi olan çekirdek alın ve demlemeden hemen önce öğütün.",
        "Türk kahvesini seviyorsanız orta kavrulmuş, tatlılığı yüksek bir tek kökeni ince öğüterek deneyin.",
        "Bir tadım (cupping) seansına katılın: Farklı kökenleri yan yana tatmak damak zevkinizi en hızlı geliştiren yoldur.",
      ] },
      { links: [{ href: "/kahve/eskisehir", label: "Eskişehir'e taze kavrum kahve" }, { href: "/coffee-bar", label: "Coffee Bar'da tadım randevusu" }, { href: "/hikayemiz", label: "Flores'in hikâyesi" }] },
    ],
  },
  {
    slug: "filtre-kahve-satin-alma-rehberi",
    title: "Filtre Kahve Satın Alırken Bilmeniz Gereken 8 Şey",
    description:
      "Filtre kahve alırken nelere dikkat edilmeli? Kavrum tarihi, çekirdek mi öğütülmüş mü, kavrum derecesi, işleme yöntemi, paket ve fiyat — doğru filtre kahveyi seçmenin kısa rehberi.",
    image: "/photos/coffee-shelf.webp",
    date: "2026-10-09",
    readMin: 5,
    blocks: [
      { p: "Market rafındaki filtre kahve ile taze kavrulmuş specialty filtre kahve arasındaki fark, ilk yudumda anlaşılır. Doğru paketi seçmek için uzman olmanıza gerek yok; şu sekiz noktaya bakmanız yeterli." },
      { h2: "1. Kavrum tarihine bakın" },
      { p: "Kahvenin tazeliğini belirleyen son kullanma tarihi değil, kavrum tarihidir. Filtre kahve, kavrumdan sonraki 1–5 hafta arasında en canlı hâlindedir. Kavrum tarihi yazmayan paketlerde kahvenin ne kadar beklediğini bilemezsiniz." },
      { h2: "2. Mümkünse çekirdek alın" },
      { p: "Öğütülmüş kahve aromasını dakikalar ve günler içinde kaybetmeye başlar. Değirmeniniz varsa çekirdek alın; yoksa kahveyi demleme yönteminize göre (V60, filtre makinesi, French Press) taze öğüten bir kavurucudan sipariş verin." },
      { h2: "3. Kökeni bilin" },
      { p: "“Ülke + bölge” bilgisi tadı tahmin etmenizi sağlar: Etiyopya çiçeksi ve meyvemsi, Kolombiya dengeli ve tatlı, Endonezya gövdeli ve baharatlı olma eğilimindedir." },
      { h2: "4. Kavrum derecesini yönteminize göre seçin" },
      { p: "Filtre için açık ve orta kavrumlar meyveyi ve tatlılığı korur. Koyu kavrum filtrede acılık ve isli notalar verebilir. Yeni başlıyorsanız orta kavrum en güvenli seçimdir." },
      { h2: "5. İşleme yöntemini okuyun" },
      { p: "Washed (yıkanmış) kahveler berrak ve temiz; natural kahveler meyvemsi ve şurupsu; honey kahveler ise ikisinin arasında, bal gibi tatlıdır. Anaerobik ve uzatılmış fermantasyonlar daha deneysel, yoğun aromalı fincanlar verir." },
      { h2: "6. Tat notalarını abartılı bir vaat değil, yön olarak görün" },
      { p: "“Çikolata, orman meyveleri, tarçın” gibi notalar kahveye eklenen aroma değildir; tadımcıların fincanda bulduğu benzerliklerdir. Size hangi yöne gittiğini söyler." },
      { h2: "7. Paketine dikkat edin" },
      { p: "Tek yönlü valfli ve tekrar kapatılabilir paketler kahvenin karbondioksitini dışarı verirken oksijeni içeri almaz. Şeffaf paketler ışık aldığı için uzun saklamaya uygun değildir." },
      { h2: "8. Fiyatı fincan başına hesaplayın" },
      { p: "250 g kahveden 15 g'lık dozla yaklaşık 16 fincan filtre kahve çıkar. Specialty bir kahvenin fincan başı maliyeti, çoğu zaman bir kafedeki filtre kahvenin küçük bir kısmıdır. Ürün sayfalarımızdaki fincan maliyeti hesaplayıcısı bunu sizin için yapar." },
      { links: [{ href: "/kategori/single-origin", label: "Filtre için tek köken kahveler" }, { href: "/rehber/filtre-kahve-nedir-nasil-hazirlanir", label: "Filtre kahve nasıl hazırlanır?" }, { href: "/rehber/cekirdek-kahve-nasil-saklanir", label: "Çekirdek kahve nasıl saklanır?" }] },
    ],
  },
  {
    slug: "evde-kahve-hazirlama-puf-noktalari",
    title: "Evde Kahve Hazırlamanın 10 Püf Noktası",
    description:
      "Evde kafe kalitesinde kahve için 10 püf noktası: taze çekirdek, doğru öğütme, terazi, su sıcaklığı, kahve-su oranı, su kalitesi ve ekipman temizliği.",
    image: "/photos/pour-over-grinder.webp",
    date: "2026-10-09",
    readMin: 5,
    blocks: [
      { p: "Evde iyi kahve yapmak pahalı ekipmandan çok birkaç doğru alışkanlığa bağlıdır. İşte fincanınızı en çok değiştirecek on küçük ayrıntı." },
      { h2: "1. Taze kavrulmuş çekirdekle başlayın" },
      { p: "Hiçbir teknik bayat kahveyi kurtaramaz. Kavrum tarihi belli, son birkaç hafta içinde kavrulmuş çekirdek kullanın." },
      { h2: "2. Demlemeden hemen önce öğütün" },
      { p: "Öğütülen kahve aromasını hızla kaybeder. İyi bir el değirmeni, pahalı bir kahve makinesinden daha büyük fark yaratır; bıçaklı değil, çarklı (burr) değirmen tercih edin." },
      { h2: "3. Göz kararı değil, terazi" },
      { p: "Bir yemek kaşığı kahve, çekirdeğin yoğunluğuna göre 5 ile 8 gram arasında değişebilir. 0,1 g hassasiyetli bir mutfak terazisi tutarlılığın anahtarıdır." },
      { h2: "4. Oranı bilin: 1:15 – 1:17" },
      { p: "Filtre kahvede başlangıç oranı 1:16'dır: 15 g kahveye 240 g su. Daha yoğun bir fincan için 1:15, daha hafif için 1:17 deneyin." },
      { h2: "5. Su sıcaklığı: 90–96 °C" },
      { p: "Kaynayan suyu 30–60 saniye bekletin. Açık kavrumlar sıcağı (94–96 °C), koyu kavrumlar biraz daha düşük sıcaklığı (88–92 °C) sever." },
      { h2: "6. Suyunuz kahvenizin %98'i" },
      { p: "Filtre kahvenin neredeyse tamamı sudur. Klor kokulu musluk suyu yerine filtrelenmiş ya da düşük mineralli kaynak suyu kullanın; arıtılmış (saf) su ise kahveyi yavan bırakır." },
      { h2: "7. Kahveyi “çiçeklendirin”" },
      { p: "Elle demlemede ilk 30–45 saniye, kahvenin iki katı kadar suyla ıslatıp bekleyin (bloom). Taze kahvedeki karbondioksit çıkar, sonraki döküşte demleme eşit olur." },
      { h2: "8. Tek seferde tek değişken" },
      { p: "Fincan ekşiyse öğütmeyi inceltin; acıysa kalınlaştırın. Aynı anda hem öğütmeyi hem oranı değiştirirseniz neyin işe yaradığını anlayamazsınız." },
      { h2: "9. Ekipmanı temiz tutun" },
      { p: "Kahve yağları zamanla acılaşır. Dripper, sürahi ve değirmeni düzenli temizleyin; kâğıt filtreyi demlemeden önce sıcak suyla yıkayın." },
      { h2: "10. Fincanı ısıtın, sıcak sıcak ama acele etmeden için" },
      { p: "Kahvenin notaları ılıdıkça açılır. İlk yudum sıcaklığı, son yudum tatlılığı ve meyveyi gösterir." },
      { links: [{ href: "/demleme-rehberi", label: "Zamanlayıcılı demleme rehberi ve oran hesaplayıcı" }, { href: "/rehber/kahve-kosesi-dekorasyonu", label: "Evde kahve köşesi nasıl kurulur?" }, { href: "/kahveler", label: "Taze kavrum kahveler" }] },
    ],
  },
  {
    slug: "kahve-hakkinda-15-gercek",
    title: "Kahve Hakkında 15 İlginç Gerçek",
    description:
      "Kahve bir meyvenin çekirdeği mi? Espresso daha mı çok kafein içerir? Türk kahvesi neden UNESCO listesinde? Kahve hakkında az bilinen 15 gerçek.",
    image: "/photos/cherries-hands.webp",
    date: "2026-10-09",
    readMin: 4,
    blocks: [
      { p: "Her gün içtiğimiz kahvenin arkasında koca bir dünya var. İşte sohbetlerde anlatabileceğiniz 15 kahve gerçeği." },
      { ul: [
        "1. Kahve çekirdeği aslında bir meyvenin, kahve kirazının çekirdeğidir. Olgun kiraz kırmızı ya da sarı renklidir ve tatlıdır.",
        "2. Dünyada ticareti yapılan kahvenin büyük kısmı iki türdendir: Arabica (yaklaşık %60) ve Robusta. Specialty kahvenin neredeyse tamamı Arabica'dır.",
        "3. Kahvenin anavatanı Etiyopya kabul edilir. Kahve meyvesini yiyen keçilerinin hareketlendiğini fark eden çoban Kaldi efsanesi buradan gelir.",
        "4. Kahve, Yengeç ve Oğlak dönenceleri arasındaki “kahve kuşağı”nda yetişir.",
        "5. Yüksek rakımda yetişen kahve daha yavaş olgunlaşır; çekirdek daha yoğun, asidite ve aroma daha karmaşık olur.",
        "6. Bir kahve fidanı ilk verimli hasadını genellikle 3–4 yılda verir.",
        "7. Dünyanın en büyük kahve üreticisi Brezilya, ikincisi Vietnam'dır.",
        "8. İngilizcede kahveye argo olarak “java” denmesi, Endonezya'nın Java adasındaki tarihî kahve üretiminden gelir.",
        "9. Türk kahvesi kültürü ve geleneği, 2013'te UNESCO Somut Olmayan Kültürel Miras listesine girdi.",
        "10. Kavrulurken kahve çekirdeği nemini kaybeder ve ağırlığının yaklaşık %15–20'sini yitirir.",
        "11. Kavrum sırasında duyulan çıtırtıya “birinci çatlama” (first crack) denir; çekirdeğin içindeki buhar ve gaz kabuğu çatlatır.",
        "12. Taze kavrulmuş kahve günlerce karbondioksit salar; kahve paketlerindeki tek yönlü valf bu yüzden vardır.",
        "13. Bir shot espresso, mililitre başına daha yoğun olsa da toplamda büyük bir fincan filtre kahveden genellikle daha az kafein içerir.",
        "14. Kavrum derecesi kafein miktarını sanıldığı kadar değiştirmez; koyu kavrum “daha sert” tadar ama daha kafeinli değildir.",
        "15. Kafeinsiz kahvelerde kafeinin en az %97'si çıkarılır; Swiss Water yönteminde bu oran %99,9'a ulaşır ve kimyasal çözücü kullanılmaz.",
      ] },
      { links: [{ href: "/rehber/kahvenin-tarihi", label: "Kahvenin tarihi" }, { href: "/kahveler/kafeinsizmeksika", label: "Swiss Water kafeinsiz Meksika" }, { href: "/rehber/endonezya-kahvesi-java", label: "Java kahvesi" }] },
    ],
  },
  {
    slug: "toptan-kahve-satin-alma-rehberi",
    title: "Toptan Kahve Satın Alma Rehberi: Kafe, Ofis ve Restoranlar İçin",
    description:
      "Kafe, ofis, otel ve restoranlar için toptan çekirdek kahve nasıl alınır? Kavrum tazeliği, kg fiyatı, kademeli fiyatlandırma, paketleme, öğütme ve tedarik düzeni üzerine pratik rehber.",
    image: "/photos/roastery-kuban.webp",
    date: "2026-10-09",
    readMin: 5,
    blocks: [
      { p: "İşletmeniz için kahve tedarikçisi seçmek, menünüzdeki en çok satan ürünün kalitesini seçmek demektir. Toptan kahve alırken yalnızca kg fiyatına bakmak yerine şu başlıkları değerlendirin." },
      { h2: "1. Tazelik ve kavrum düzeni" },
      { p: "Toptan alımda en sık yapılan hata, aylarca yetecek kahveyi bir kerede almaktır. Kahve kavrumdan sonraki birkaç hafta içinde en iyi hâlindedir; 2–4 haftalık tüketiminizi planlayıp düzenli siparişle ilerlemek fincan kalitesini korur." },
      { h2: "2. Kullanım amacına göre kavrum" },
      { ul: ["Espresso ve sütlü içecekler: gövdeli, tatlı, düşük asiditeli profiller", "Filtre kahve ve batch brew: açık-orta kavrum, meyvemsi ve temiz profiller", "Omni kavrum: hem filtre hem espresso için orta yol — tek çekirdekle iki menü"] },
      { h2: "3. Kademeli fiyatlandırma" },
      { p: "Toptan kahvede kg fiyatı genellikle miktar arttıkça düşer. Flores'te toptan sipariş en az 5 kg'dan başlar ve her çekirdeğin kendi kademeleri vardır; örneğin bir çekirdekte belirli bir kg'yi geçtiğinizde kg fiyatı otomatik olarak indirimli kademeye iner." },
      { h2: "4. Paket boyu ve türü" },
      { p: "Yoğun bir kafe için 1 kg paketler pratiktir; ofis ve otel odaları için 250 g ya da 100 g paketler tazeliği korur. Valfli doypack, kraft ya da markanıza uygun renkli paket seçenekleri sunan bir kavurucu tercih edin." },
      { h2: "5. Öğütme" },
      { p: "Kendi değirmeniniz varsa çekirdek alın. Yoksa ekipmanınıza (filtre makinesi, French Press, espresso) göre öğütülmüş kahve isteyin ve daha küçük, daha sık sipariş verin." },
      { h2: "6. Destek ve eğitim" },
      { p: "İyi bir tedarikçi yalnızca kahve satmaz: reçete, öğütme ayarı ve ekipman konusunda yardım eder; menünüzü birlikte kurar. Tadım yapmadan karar vermeyin — numune ya da tadım seansı isteyin." },
      { h2: "Flores ile toptan sipariş" },
      { p: "Sitemizdeki toptan sipariş oluşturucuda çekirdekleri, kavrum tipini (filtre, espresso, omni), öğütmeyi, paket boyunu ve paket türünü seçip kademeli fiyatı anında görebilir, siparişinizi doğrudan verebilirsiniz. Özel ihtiyaçlar için teklif formumuz da açık." },
      { links: [{ href: "/toptan", label: "Toptan sipariş oluşturucu" }, { href: "/iletisim", label: "İletişim ve teklif" }, { href: "/rehber/hangi-demleme-icin-hangi-kahve", label: "Hangi demleme için hangi kahve?" }] },
    ],
  },
  {
    slug: "kahve-kosesi-dekorasyonu",
    title: "Evde Kahve Köşesi Nasıl Kurulur? Dekorasyon ve Ekipman Rehberi",
    description:
      "Evde kahve köşesi (coffee corner) kurmak için fikirler: doğru yer, temel ekipman listesi, saklama kavanozları, raf düzeni ve dekorasyon önerileri.",
    image: "/photos/brew-kit.webp",
    date: "2026-10-09",
    readMin: 4,
    blocks: [
      { p: "Sabah ritüelinizi güzelleştirmenin en kolay yolu, kahveye ait küçük bir köşe kurmak. Mutfak tezgâhının bir ucu, bir konsol ya da duvar rafı yeterli; önemli olan her şeyin elinizin altında ve düzenli olması." },
      { h2: "Doğru yeri seçin" },
      { p: "Prize ve suya yakın, doğrudan güneş almayan bir yer seçin. Ocak ve fırının hemen yanı, ısı ve nem yüzünden çekirdekler için uygun değildir." },
      { h2: "Temel ekipman listesi" },
      { ul: [
        "Çarklı (burr) kahve değirmeni — el ya da elektrikli",
        "Dripper (V60, Origami, Kalita) ve kâğıt filtreler veya French Press / AeroPress",
        "Kuğu boyunlu kettle (mümkünse sıcaklık ayarlı)",
        "0,1 g hassasiyetli terazi",
        "Cam sürahi ve sevdiğiniz fincanlar",
      ] },
      { h2: "Saklama: kavanoz değil, hava almayan kap" },
      { p: "Cam kavanozlarda sergilenen çekirdekler güzel görünür ama ışık ve hava tazeliği hızla düşürür. Sergilemek istiyorsanız haftalık tüketiminizi koyun; asıl stoku valfli paketinde ya da ışık geçirmeyen hava almaz kapta saklayın." },
      { h2: "Dekorasyon önerileri" },
      { ul: [
        "Doğal malzemeler: ahşap tepsi, mermer altlık, deri ya da keten detaylar",
        "Bir duvar rafı: fincanlar, demleme notları ve kahve kitapları için",
        "Bitki: kahve bitkisi (Coffea arabica) ev içinde aydınlık ve dolaylı ışıkta yetişebilir",
        "Kahve paketlerinizi ve kutularınızı sergileyin — Flores kutuları bunun için tasarlandı",
        "Küçük bir tahta ya da kart: haftanın kahvesi ve reçetesi",
      ] },
      { h2: "Düzen için bir kural" },
      { p: "Her demlemeden sonra dripper'ı yıkayın, terazi ve kettle'ı yerine koyun. Kahve köşesi ancak dağınık değilken her sabah sizi çağırır." },
      { links: [{ href: "/kategori/accessories", label: "Demleme aksesuarları" }, { href: "/rehber/evde-kahve-hazirlama-puf-noktalari", label: "Evde kahve hazırlamanın püf noktaları" }, { href: "/kategori/sets", label: "Hediye kutuları ve setler" }] },
    ],
  },
  {
    slug: "drip-coffee-vs-pour-over",
    title: "Drip Coffee mi, Pour Over mı? Filtre Makinesi ile Elle Demleme Farkı",
    description:
      "Drip coffee (filtre kahve makinesi) ile pour over (V60, Chemex, Kalita) arasındaki farklar: tat, kontrol, pratiklik, ekipman ve hangi kahvenin hangisine uygun olduğu.",
    image: "/photos/v60-bar.webp",
    date: "2026-10-09",
    readMin: 4,
    blocks: [
      { p: "İkisi de filtre kahvedir: Sıcak su öğütülmüş kahvenin üzerinden geçer, kâğıt ya da metal filtre telvesini tutar. Fark, suyu kimin döktüğündedir — makine mi, siz mi?" },
      { h2: "Drip coffee (filtre kahve makinesi)" },
      { p: "Makine suyu ısıtır ve duşlama başlığıyla kahvenin üzerine damlatır. En büyük avantajı pratikliktir: Bir düğmeyle 1 litreye kadar kahve hazırlanır, ofis ve kalabalık sofralar için idealdir. Kaliteli bir makine (doğru sıcaklıkta su veren, suyu kahveye eşit dağıtan) çok iyi sonuç verir." },
      { h2: "Pour over (elle demleme)" },
      { p: "V60, Chemex, Kalita, Origami gibi demleyicilerde suyu kuğu boyunlu bir kettle ile siz dökersiniz. Su sıcaklığını, döküş hızını, çiçeklenme süresini ve toplam süreyi kontrol edersiniz. Bu kontrol, açık kavrulmuş ve aromatik kahvelerin çiçeksi ve meyvemsi notalarını açığa çıkarmak için büyük avantajdır." },
      { h2: "Karşılaştırma" },
      { ul: [
        "Tat: Pour over daha berrak ve katmanlı; drip daha yuvarlak ve tutarlı.",
        "Kontrol: Pour over'da her değişken sizde; drip'te makinenin ayarlarına bağlısınız.",
        "Pratiklik: Drip açık ara önde; pour over 3–4 dakikalık bir ritüel ister.",
        "Miktar: Drip tek seferde çok fincan; pour over genellikle 1–2 fincan.",
        "Öğütme: İkisinde de orta-ince/orta; drip için genellikle biraz daha kalın.",
      ] },
      { h2: "Hangi kahve hangisine?" },
      { p: "Tatlı ve dengeli, orta kavrulmuş kahveler (ör. Manis Etiyopya Sidamo, El Salvador Ochuspe) filtre makinesinde çok başarılıdır. Çiçeksi, meyvemsi ve deneysel işlemeli kahveler (Guntur Honey, Frinsa #3) pour over'da en iyi hâlini gösterir." },
      { links: [{ href: "/rehber/v60-demleme-receteleri", label: "V60 demleme reçeteleri" }, { href: "/rehber/filtre-kahve-nedir-nasil-hazirlanir", label: "Filtre kahve nedir, nasıl hazırlanır?" }, { href: "/demleme-rehberi", label: "Zamanlayıcılı demleme rehberi" }] },
    ],
  },
  {
    slug: "barista-nedir",
    title: "Barista Nedir, Ne İş Yapar? Baristalık Hakkında Merak Edilenler",
    description:
      "Barista kimdir, ne iş yapar, nasıl barista olunur? Espresso, süt köpürtme, latte art, filtre demleme ve kahve bilgisi — baristalık mesleğini ve gerekli becerileri anlatıyoruz.",
    image: "/photos/espresso-machine.webp",
    date: "2026-10-09",
    readMin: 4,
    blocks: [
      { p: "Barista, İtalyancada bar arkasında hizmet veren kişi anlamına gelir. Bugün ise kahveyi hazırlayan, ekipmanı ayarlayan ve misafire kahveyi anlatan profesyoneli tanımlar. İyi bir barista, kavurucunun aylarca emek verdiği çekirdeği fincana doğru taşıyan son halkadır." },
      { h2: "Barista ne iş yapar?" },
      { ul: [
        "Espresso kalibrasyonu: Her sabah öğütmeyi, dozu ve süreyi ayarlayarak espressoyu “dial-in” eder.",
        "Süt hazırlığı: Sütü doğru sıcaklıkta ve ipeksi mikroköpükle köpürtür; latte art yapar.",
        "Filtre demleme: V60, Chemex, batch brew gibi yöntemlerle filtre kahve hazırlar.",
        "Misafir deneyimi: Kahvenin kökenini, tat notalarını anlatır, damak zevkine göre öneri yapar.",
        "Hijyen ve bakım: Makine, değirmen ve ekipmanın temizliğinden sorumludur.",
      ] },
      { h2: "Nasıl barista olunur?" },
      { p: "Baristalık büyük ölçüde pratikle öğrenilir. Bir kafede çalışmaya başlamak, temel espresso ve süt tekniklerini usta bir baristadan öğrenmek en hızlı yoldur. Specialty Coffee Association (SCA) gibi kuruluşların barista, demleme ve duyusal analiz eğitimleri bilgiyi sistemli hâle getirir." },
      { h2: "İyi bir baristada aranan özellikler" },
      { p: "Hassas bir damak, tutarlılık, hız altında sakin kalabilmek ve misafirle iletişim. Kahvenin tarımından kavrumuna kadar zinciri merak etmek ise iyi bir baristayı harika bir baristaya dönüştürür." },
      { h2: "Evde barista gibi" },
      { p: "Evde barista olmak için profesyonel makine şart değil: İyi bir değirmen, terazi ve taze kahveyle filtre kahvede kafe kalitesine ulaşabilirsiniz. Coffee Bar'ımızda baristalarımızla kahve tadabilir, sorularınızı sorabilirsiniz." },
      { links: [{ href: "/coffee-bar", label: "Coffee Bar'da tadım" }, { href: "/kategori/espresso", label: "Espresso kahveleri" }, { href: "/rehber/evde-kahve-hazirlama-puf-noktalari", label: "Evde kahve hazırlamanın püf noktaları" }] },
    ],
  },
  {
    slug: "nitelikli-kahve-nasil-secilir",
    title: "Nitelikli Kahve Nedir, Nasıl Seçilir? Etiket Okuma Rehberi",
    description:
      "Nitelikli (specialty) kahve nasıl seçilir? Paket etiketindeki köken, rakım, işleme yöntemi, çeşit, kavrum tarihi ve tat notalarını okumayı öğrenin; damak zevkinize uygun kahveyi bulun.",
    image: "/photos/cupping-pour.webp",
    date: "2026-10-09",
    readMin: 5,
    blocks: [
      { p: "Nitelikli kahve, kökeni izlenebilen, özenle yetiştirilip işlenen ve uzman tadımcılardan 100 üzerinden 80 ve üzeri puan alan kahvedir. Peki rafta ya da bir sitede doğru kahveyi nasıl seçersiniz? Cevap, etiketi okumakta." },
      { h2: "Etiketteki bilgiler ne anlatır?" },
      { ul: [
        "Köken: Ülke ve bölge. Tat profilinin ilk ipucu.",
        "Rakım: Genellikle 1.200 metrenin üzeri. Yüksek rakım çoğunlukla daha canlı asidite ve karmaşık aroma demektir.",
        "Çeşit (varyete): Bourbon, Typica, Geisha, Etiyopya yerel çeşitleri gibi. Şaraptaki üzüm türü gibi düşünün.",
        "İşleme: Washed, natural, honey, anaerobik. Tatlılık ve meyve yoğunluğunu belirler.",
        "Kavrum tarihi: Tazeliğin tek güvenilir göstergesi.",
        "Tat notaları: Kahvenin hangi yöne gittiğini gösteren rehber.",
      ] },
      { h2: "Damak zevkinize göre seçim" },
      { ul: [
        "Acı ve ekşi sevmiyor, tatlı ve yumuşak istiyorum: orta kavrum, çikolata-karamel notaları (ör. Manis, Pagi).",
        "Meyvemsi ve canlı fincanları seviyorum: açık kavrum, natural ya da honey işleme (ör. Guntur, Frinsa).",
        "Sütlü içiyorum: gövdeli, düşük asiditeli profiller (ör. Tanah, Arjuna).",
        "Kafeinden kaçınıyorum: Swiss Water yöntemiyle kafeinsizleştirilmiş kahve.",
      ] },
      { h2: "Fiyat ve puan" },
      { p: "Mikrolotlar, deneysel fermantasyonlar ve nadir çeşitler daha pahalıdır; ama günlük içim için en pahalı kahve şart değildir. Tutarlı, taze ve sevdiğiniz profilde bir kahve, her gün içtiğinizde en iyi yatırımdır." },
      { h2: "Kavurucuyu tanıyın" },
      { p: "Kahvesini haftalık kavuran, künyesini açıkça paylaşan ve sorularınıza cevap veren bir kavurucu seçin. Flores'te her kahvenin kutusunda ve ürün sayfasında tüm künye ve saniye saniye demleme tarifi yer alır." },
      { links: [{ href: "/rehber/3-nesil-kahve-nedir", label: "3. nesil (specialty) kahve nedir?" }, { href: "/rehber/single-origin-kahve-nedir", label: "Single origin kahve nedir?" }, { href: "/kahveler", label: "Tüm kahvelerimiz" }] },
    ],
  },
  {
    slug: "kahvenin-tarihi",
    title: "Kahvenin Tarihi: Etiyopya'dan Yemen'e, İstanbul'dan Java'ya",
    description:
      "Kahvenin kısa tarihi: Etiyopya'daki keşif efsanesi, Yemen ve Mocha limanı, İstanbul'un ilk kahvehaneleri, Java'ya ve Latin Amerika'ya yayılış, espresso ve 3. dalga kahve.",
    image: "/photos/story-indonesia.webp",
    date: "2026-10-09",
    readMin: 6,
    blocks: [
      { p: "Bugün dünyanın her köşesinde içilen kahvenin yolculuğu, Etiyopya'nın dağlık ormanlarında başladı. Bu yolculuk ticaret yollarını, şehirleri ve sohbet kültürünü değiştirdi." },
      { h2: "Etiyopya: efsane ve anavatan" },
      { p: "Kahvenin anavatanı Etiyopya kabul edilir. Anlatılan efsaneye göre çoban Kaldi, kırmızı meyveleri yiyen keçilerinin gece boyu uyumadığını fark eder. Efsane bir yana, Arabica kahvesinin genetik çeşitliliğinin en yüksek olduğu yer bugün de Etiyopya'dır." },
      { h2: "Yemen ve Mocha" },
      { p: "15. yüzyılda kahvenin bugünkü gibi demlenip içildiğine dair ilk güvenilir kayıtlar Yemen'den gelir; Sufi dervişler gece ibadetlerinde uyanık kalmak için kahve içerdi. Yemen'in Mocha limanı yüzyıllar boyunca dünya kahve ticaretinin merkezi oldu — “mocha” adı buradan gelir." },
      { h2: "İstanbul ve kahvehaneler" },
      { p: "Kahve 16. yüzyılda Osmanlı topraklarına ulaştı; İstanbul'da 1550'lerde açılan ilk kahvehaneler kısa sürede sohbetin, şiirin ve haberin merkezi oldu. Cezvede pişirilen, telvesiyle sunulan Türk kahvesi bu dönemde şekillendi ve bugün UNESCO'nun somut olmayan kültürel miras listesinde yer alıyor." },
      { h2: "Avrupa ve Java" },
      { p: "17. yüzyılda kahvehaneler Venedik, Londra, Paris ve Viyana'da yayıldı. Kahve tekelini kırmak isteyen Hollandalılar, 17. yüzyılın sonunda kahveyi Endonezya'nın Java adasına taşıdı. Java kahvesi öylesine ünlendi ki İngilizcede “java” kahvenin takma adı oldu. Bugün Batı Java'nın volkanik yamaçları, Ruso Exotics serimizin de evi." },
      { h2: "Latin Amerika" },
      { p: "18. yüzyılda kahve Karayipler'e, Orta ve Güney Amerika'ya ulaştı. Brezilya kısa sürede dünyanın en büyük üreticisi oldu; Kolombiya, El Salvador ve Meksika gibi ülkeler de bugünün önemli kahve kökenleri arasında." },
      { h2: "Espresso, filtre ve 3. dalga" },
      { p: "20. yüzyıl kahveyi yeniden icat etti: Melitta Bentz 1908'de kâğıt filtreyi buldu, İtalya'da gelişen espresso makineleri kremalı espressoyu ve kafe kültürünü doğurdu. Yüzyılın sonunda ise “specialty coffee” kavramı doğdu; 2000'lerde 3. dalga kahve, kökeni, üreticiyi ve taze kavrumu fincanın merkezine koydu." },
      { links: [{ href: "/rehber/etiyopya-kahvesi", label: "Etiyopya kahvesi" }, { href: "/rehber/endonezya-kahvesi-java", label: "Endonezya ve Java kahvesi" }, { href: "/rehber/kahve-hakkinda-15-gercek", label: "Kahve hakkında 15 gerçek" }] },
    ],
  },
  {
    slug: "filtre-kahve-nedir-nasil-hazirlanir",
    title: "Filtre Kahve Nedir, Nasıl Hazırlanır? Makine, V60, Chemex ve French Press",
    description:
      "Filtre kahve nedir, nasıl yapılır? Filtre kahve makinesi, V60, Chemex ve French Press ile adım adım filtre kahve hazırlama; oran, öğütme ve su sıcaklığı tablosu.",
    image: "/photos/pour-over.webp",
    date: "2026-10-09",
    readMin: 5,
    blocks: [
      { p: "Filtre kahve, öğütülmüş kahvenin sıcak suyla demlenip bir filtreden süzülmesiyle hazırlanan kahvedir. Basınç kullanılmadığı için espressodan daha hafif gövdeli, daha berrak ve aromatiktir; kahvenin kökenini en net gösteren yöntemlerden biridir." },
      { h2: "Temel kurallar" },
      { ul: ["Oran: 1:16 (ör. 15 g kahve / 240 g su)", "Su sıcaklığı: 90–96 °C", "Öğütme: orta (yönteme göre ince-orta ile kalın arası)", "Toplam süre: 2:30 – 4:00 dakika (French Press'te 4 dakika)"] },
      { h2: "Filtre kahve makinesiyle" },
      { ul: [
        "Her fincan (240 ml) için 15 g orta öğütülmüş kahve ölçün.",
        "Kâğıt filtreyi sıcak suyla ıslatın, kahveyi yerleştirip yüzeyi düzleyin.",
        "Hazneye taze, filtrelenmiş su koyun ve makineyi çalıştırın.",
        "Demleme bitince sürahiyi çalkalayın ve hemen servis edin; ocakta uzun süre bekletmeyin.",
      ] },
      { h2: "V60 ile" },
      { p: "15 g orta-ince kahve, 240 g 93–94 °C su. 30 g suyla 40 saniye çiçeklendirin, ardından dairesel ve yavaş döküşlerle 2:00'a kadar suyu tamamlayın; toplam süre 2:45–3:15 olmalı. Ayrıntılı tarifler için V60 reçeteleri yazımıza bakın." },
      { h2: "Chemex ile" },
      { p: "Kalın Chemex filtresi daha temiz ve tatlı bir fincan verir. 30 g orta-kalın kahve, 500 g su; 60 g ile çiçeklendirme, ardından üç dört döküş. Toplam süre 4:00 civarı." },
      { h2: "French Press ile" },
      { p: "15 g kalın öğütülmüş kahveye 240 g sıcak su ekleyin, 4 dakika bekleyin. Üstteki kabuğu kırıp köpüğü alın, pistonu yavaşça bastırın ve hemen fincana boşaltın. Metal filtre yağları geçirdiği için gövdeli, dolgun bir fincan çıkar." },
      { h2: "Hangi kahve?" },
      { p: "Filtre için açık ve orta kavrulmuş tek köken kahveler idealdir. Tatlı ve dengeli bir başlangıç için Manis (Etiyopya · Sidamo), meyvemsi bir fincan için Guntur Honey ya da Frinsa'yı deneyin." },
      { links: [{ href: "/demleme-rehberi", label: "Zamanlayıcılı demleme rehberi" }, { href: "/rehber/v60-demleme-receteleri", label: "V60 demleme reçeteleri" }, { href: "/rehber/drip-coffee-vs-pour-over", label: "Drip coffee mi, pour over mı?" }] },
    ],
  },
  {
    slug: "v60-demleme-receteleri",
    title: "V60 Demleme Reçeteleri: 6 Farklı Tarif (Klasik, 4:6, Buzlu V60…)",
    description:
      "V60 demleme reçeteleri arşivi: klasik 1:16 tarif, 4:6 yöntemi, tek döküş, açık kavrum için yüksek oran, buzlu (Japon usulü) V60 ve tatlı orta kavrum tarifi — gram, sıcaklık ve süreleriyle.",
    image: "/photos/v60-pour.webp",
    date: "2026-10-09",
    readMin: 6,
    blocks: [
      { p: "V60, küçük değişikliklerle bambaşka fincanlar verir. Aşağıdaki tarifler bir başlangıç noktasıdır: Hepsinde taze kavrulmuş kahve, 0,1 g terazi ve kuğu boyunlu kettle kullanın; kâğıt filtreyi önce sıcak suyla yıkayın." },
      { h2: "1. Klasik günlük tarif (1:16)" },
      { ul: ["15 g kahve, orta-ince öğütme · 240 g su, 93 °C", "0:00 – 30 g su ile çiçeklendirme, 40 sn bekle", "0:40 – 1:10 arası 150 g'a kadar dairesel döküş", "1:10 – 1:40 arası 240 g'a tamamla, hafifçe çalkala", "Hedef toplam süre: 2:45 – 3:15"] },
      { h2: "2. 4:6 yöntemi" },
      { p: "Japon barista Tetsu Kasuya'nın popülerleştirdiği bu yöntemde su beş eşit döküşe bölünür: İlk iki döküş (%40) tatlılık-asidite dengesini, son üç döküş (%60) yoğunluğu belirler." },
      { ul: ["20 g kahve, orta-kalın öğütme · 300 g su, 92 °C", "Her 45 saniyede bir 60 g döküş: 0:00, 0:45, 1:30, 2:15, 3:00", "Daha tatlı fincan için ilk döküşü 50 g, ikinciyi 70 g yapın; daha asidik için tersini", "Toplam süre: ~3:30"] },
      { h2: "3. Tek döküş (pratik tarif)" },
      { ul: ["15 g kahve, orta öğütme · 250 g su, 94 °C", "40 g su ile 30 sn çiçeklendirme", "Kalan suyu merkeze yakın, tek ve yavaş bir döküşle 1:30'a kadar tamamla", "Toplam süre: ~2:45"] },
      { h2: "4. Açık kavrum ve deneysel işlemeler için (1:17)" },
      { ul: ["15 g kahve, biraz daha ince öğütme · 255 g su, 95–96 °C", "45 g ile 45 sn çiçeklendirme", "Üç eşit döküşle (70 g) 1:45'e kadar tamamla", "Çiçeksi ve meyvemsi notalar için: Guntur Honey, Frinsa #3, Watermelon"] },
      { h2: "5. Buzlu V60 (Japon usulü)" },
      { p: "Suyun bir kısmı yerine sürahiye buz koyulur; sıcak demlenen kahve buzun üzerine damlayarak anında soğur ve aromalarını korur." },
      { ul: ["20 g kahve, ince-orta öğütme", "Sürahiye 120 g buz · demleme için 180 g su, 94 °C", "40 g ile 40 sn çiçeklendirme, ardından 2:00'a kadar 180 g'a tamamla", "Çalkalayıp buzlu bardağa servis edin; meyvemsi kahvelerle çok ferah olur"] },
      { h2: "6. Tatlı ve yumuşak orta kavrum tarifi" },
      { ul: ["16 g kahve, orta öğütme · 250 g su, 91–92 °C", "35 g ile 45 sn çiçeklendirme", "İki döküşle 1:30'a kadar tamamla, sakin ve düşük akış", "Çikolata ve tarçın notalarını öne çıkarır — Manis (Etiyopya · Sidamo) için önerimiz"] },
      { h2: "Sorun giderme" },
      { p: "Demleme 2:30'dan kısa sürüyor ve fincan ekşiyse öğütmeyi inceltin. 4:00'ı geçiyor ve fincan acı-kuruysa kalınlaştırın. Her seferinde tek bir değişkeni değiştirin ve not alın." },
      { links: [{ href: "/demleme-rehberi", label: "Zamanlayıcılı demleme rehberi ve oran hesaplayıcı" }, { href: "/rehber/v60-ile-filtre-kahve-nasil-demlenir", label: "V60 ile filtre kahve adım adım" }, { href: "/kahveler/manis-blend-espresso-filtre", label: "Manis Etiyopya Sidamo" }] },
    ],
  },
];
