/**
 * FLORES ROASTERY KATALOĞU
 * ------------------------
 * Ürün künyeleri floresroastery.com ürün sayfalarından, fiyat / paket / SKU /
 * stok bilgileri WooCommerce Store API'den (Ekim 2026) alınmıştır.
 * WooCommerce bağlandığında fiyat ve stok canlı veriden gelir; buradaki
 * editoryal alanlar (künye, demleme, kavurma) korunur. Bkz. woocommerce.ts
 */
import { photos } from "@/lib/photos";
import { chemex, espresso, frenchPress, kalita, v60 } from "./brew";
import type { Category, Product, ProductVariant, TastingNote } from "./types";

export const categories: Category[] = [
  {
    slug: "single-origin",
    name: "Single Origin",
    tagline: "Tek bir bölgenin, tek bir hasadın imzası.",
    description:
      "Tek bir ülke, bölge ve çoğu zaman tek bir üreticiden gelen kahveler. Java'nın volkanik yamaçlarından El Salvador'un aile çiftliklerine; toprağın, rakımın ve işleme yönteminin izini fincanda en saf hâliyle taşır.",
    image: photos.coffeeBarJars,
  },
  {
    slug: "blends",
    name: "Blends",
    tagline: "Etiyopya ile Endonezya, aynı fincanda.",
    description:
      "Manis, Pagi ve Tanah: Etiyopya'nın meyvesini Endonezya'nın gövdesiyle buluşturan günlük harmanlarımız. Adlarını Endonezce'den alırlar — tatlı, sabah ve toprak.",
    image: photos.coffeeShelf,
  },
  {
    slug: "espresso",
    name: "Espresso",
    tagline: "Basınç altında parlayan gövde ve tatlılık.",
    description:
      "Espressoda ve sütlü içeceklerde parlayan kahveler. Yoğun gövde, uzun bitiş ve kremalı doku; moka pot ve Türk kahvesi için de güvenilir seçimler.",
    image: photos.espressoMachine,
  },
  {
    slug: "sets",
    name: "Sets & Boxes",
    tagline: "Hediye etmek ya da tadarak keşfetmek için.",
    description:
      "Endonezya serisinin dört çekirdeğini ya da Manis, Pagi ve Tanah harmanlarını bir arada deneyin. Hediye kutuları ve keşif setleri; her biri haftalık taze kavrum.",
    image: photos.boxesNature,
  },
  {
    slug: "accessories",
    name: "Accessories",
    tagline: "Demleme masanız için el yapımı parçalar.",
    description: "El yapımı deri kettle ve filtre kağıdı kılıfları — demleme ritüelinize Flores dokunuşu.",
    image: photos.brewKit,
  },
];

/* ------------------------------------------------------------------ */

const note = (label: string, color: string): TastingNote => ({ label, color });

const N = {
  karamel: note("Karamel", "#d99a4e"),
  esmerSeker: note("Esmer Şeker", "#c8915a"),
  misketLimonu: note("Misket Limonu", "#b5d65a"),
  kakao: note("Kakao", "#8c5f48"),
  baharat: note("Baharat", "#c0703f"),
  beyazUzum: note("Beyaz Üzüm", "#d7e2a0"),
  kuruUzum: note("Altın Kuru Üzüm", "#d9a441"),
  kanPortakali: note("Kan Portakalı", "#e2553f"),
  kirmiziMeyve: note("Kırmızı Meyveler", "#c2334d"),
  yabanMersini: note("Yaban Mersini", "#6e6fd0"),
  bogurtlen: note("Böğürtlen", "#6f4a8e"),
  erik: note("Erik", "#9b3f74"),
  ciceksi: note("Çiçeksi", "#d9cdf2"),
  seftali: note("Şeftali", "#f2a97e"),
  sariElma: note("Sarı Elma", "#e6cf5c"),
  karpuz: note("Karpuz", "#ef5a6f"),
  balKavunu: note("Bal Kavunu", "#b9dc8c"),
  nane: note("Nane", "#6fcf9f"),
  cikolata: note("Çikolata", "#8a5a44"),
  sutluCikolata: note("Sütlü Çikolata", "#b07a5a"),
  findik: note("Fındık", "#c49a6c"),
  ormanMeyveleri: note("Orman Meyveleri", "#8e3b6e"),
  tarcin: note("Tarçın", "#b8693b"),
  badem: note("Badem", "#e0c09a"),
  bitterCikolata: note("Bitter Çikolata", "#6b4433"),
  kuruyemis: note("Kavrulmuş Kuruyemiş", "#a8784c"),
  ahududu: note("Ahududu", "#e0457b"),
  bergamot: note("Bergamot", "#e8d27a"),
  portakalKabugu: note("Portakal Kabuğu", "#f0963c"),
  kakaoNibs: note("Kakao Nibs", "#7a5040"),
};

/** [Woo varyasyon id, gram, fiyat, liste fiyatı?, stokta?] */
type V = [id: number, grams: number, price: number, compareAt?: number, inStock?: boolean];
const variants = (sku: string, rows: V[]): ProductVariant[] =>
  rows.map(([id, grams, price, compareAt, inStock = true]) => ({
    id: String(id),
    sku,
    weight: grams,
    label: grams >= 1000 ? `${grams / 1000} kg` : `${grams} g`,
    price,
    compareAtPrice: compareAt && compareAt > price ? compareAt : undefined,
    inStock,
  }));
const soldOut = (rows: ProductVariant[]) => rows.map((v) => ({ ...v, inStock: false }));

import { GRIND_OPTIONS } from "./grind";
export { GRIND_OPTIONS };

const img = (slug: string, bg: string, packaging: "box" | "pouch" = "box", aspect = 1.09) => ({
  card: `/coffees/${slug}.webp`,
  front: `/coffees/${slug}-front.webp`,
  bg,
  packaging,
  aspect,
});

/* ------------------------------------------------------------------ */

export const products: Product[] = [
  {
    id: "1424",
    slug: "guntur-endonezya",
    name: "Guntur",
    fullName: "Guntur Endonezya Honey",
    subtitle: "Endonezya · Garut, Batı Java",
    categories: ["single-origin"],
    collection: "ruso-exotics",
    limited: true,
    headline: "Java dağlarında bir çiçek bahçesi",
    origin: { country: "Endonezya", region: "Garut, Batı Java", producer: "Redi Purnawan" },
    elevation: "1200 – 1500 m",
    process: "Honey",
    variety: ["Typica", "Ateng", "Catimor", "Yellow Bourbon"],
    harvest: "El ile seçilmiş olgun kirazlar",
    roastLevel: "Açık",
    recommendedFor: "Filtre",
    tastingNotes: [N.ciceksi, N.seftali, N.sariElma, N.esmerSeker],
    bodyAcidity: "Orta gövde, parlak meyvemsi asidite, ipeksi doku",
    facts: [{ label: "Marka / Tedarik", value: "Ruso Exotics (Direct Trade)" }],
    description:
      "Guntur Endonezya Honey kahve çekirdeği — Batı Java, Garut'tan; çiçeksi, şeftali, sarı elma ve esmer şeker notalarıyla parlak, ipeksi bir filtre kahve.",
    story: [
      "Endonezya'nın Batı Java bölgesindeki Garut'un sisli yamaçlarından gelen Guntur Honey, alışılmışın dışında bir Java deneyimi sunuyor. Ünlü üretici Redi Purnawan'ın titiz işçiliğiyle hayat bulan bu kahve; Typica, Ateng ve nadir bulunan Yellow Bourbon çeşitlerinin sofistike bir birleşimi.",
      "Bir bahar sabahı gibi ferahlatıcı: ilk yudumda karşılayan çiçeksi notalar kısa sürede yerini şeftali ve sulu sarı elmanın tatlılığına bırakıyor; esmer şeker derinliği meyveyi dengeliyor. Honey işlemde müsilajın bir kısmı çekirdek üzerinde bırakılarak kurutulur — bal tatlılığı buradan gelir.",
      "Ruso Exotics'in doğrudan ticaret felsefesiyle, üreticimiz Redi Purnawan ile bizzat el sıkışarak seçtiğimiz sınırlı stoklu bir lot.",
    ],
    image: img("guntur-endonezya", "#dca93d"),
    variants: variants("SKU-END-GNT", [
      [1427, 100, 300, 375],
      [1428, 200, 600, 700],
      [1426, 500, 1200, 1500],
    ]),
    grindOptions: GRIND_OPTIONS,
    brewGuides: {
      filter: v60({ temperature: 93, tip: "Çiçeksi açılış için 93 °C su ve ince, sakin bir spiral döküş." }),
    },
    featured: true,
  },
  {
    id: "1244",
    slug: "el-savador-ochuspe",
    name: "Ochuspe",
    fullName: "El Salvador Ochuspe — Doğal Anaerobik 60 Saat",
    subtitle: "El Salvador · Santa Ana",
    categories: ["single-origin", "espresso"],
    headline: "Apaneca-Ilamatepec volkanlarından",
    origin: { country: "El Salvador", region: "Santa Ana, Apaneca-Ilamatepec", producer: "Mauricio Escalón", farm: "Finca Ochuspe" },
    elevation: "1250 m",
    process: "Doğal Anaerobik · 60 saat",
    variety: ["Bourbon", "Pacas", "Colombia"],
    harvest: "2024 / 2025",
    roastLevel: "Açık-Orta",
    recommendedFor: "Filtre & Espresso",
    tastingNotes: [N.beyazUzum, N.kuruUzum, N.karamel],
    score: 85,
    description:
      "El Salvador Finca Ochuspe doğal anaerobik kahve çekirdeği — beyaz üzüm, altın kuru üzüm ve karamel notaları; 85 SCA puanlı, espresso ve filtreye uygun.",
    story: [
      "El Salvador'un Santa Ana bölgesindeki Apaneca-Ilamatepec volkanik dağlarının zengin topraklarında yetişen bu kahve, dört nesillik kahve üreticisi Mauricio Escalón'un aile mirasının bir parçası.",
      "1.250 metre rakımda elle toplanan kirazlar, 60 saat boyunca oksijensiz ortamda fermente edilir. Bu süreç, aşırı fermantasyona kaçmadan yoğun aromatik bir profil kazandırır: fincanda beyaz üzüm ve altın kuru üzümün meyvemsi tatlılığı, dengeli bir karamel gövdeyle birleşir.",
    ],
    image: img("el-savador-ochuspe", "#c9cf8d"),
    variants: variants("SKU-ELS-OCH", [
      [1247, 100, 240, 300],
      [1248, 200, 440, 550],
      [1246, 500, 800, 1000],
      [1245, 1000, 1480, 1850],
    ]),
    grindOptions: GRIND_OPTIONS,
    brewGuides: {
      filter: kalita({ tip: "Anaerobik meyveyi öne çıkarmak için Kalita Wave'in düz yatağı idealdir." }),
      espresso: espresso({ output: 40, time: 28, tip: "Sade espressoda kuru üzüm ve karamel; sütle karamelli bir latte." }),
    },
    featured: true,
  },
  {
    id: "1746",
    slug: "frinsa3",
    name: "Frinsa #3",
    fullName: "Endonezya Frinsa #3 — Extended Natural",
    subtitle: "Endonezya · Weninggalih, Batı Java",
    categories: ["single-origin"],
    headline: "Lactobacillus ile 72 saat",
    origin: { country: "Endonezya", region: "Weninggalih, Batı Java", producer: "Wildan Mustofa", farm: "Java Frinsa Estate" },
    elevation: "1400 m",
    process: "Extended Natural · 72 saat yarı anaerobik Lactobacillus",
    variety: [],
    harvest: "",
    roastLevel: "Açık",
    recommendedFor: "Filtre",
    tastingNotes: [N.kanPortakali, N.kirmiziMeyve],
    bodyAcidity: "Orta-tam, şurupsu gövde; canlı, parlak ve meyvemsi asidite",
    description:
      "Endonezya Frinsa #3 Extended Natural kahve çekirdeği — 72 saat Lactobacillus fermantasyonu; kan portakalı ve kırmızı meyve notalarıyla şurupsu, tatlı bir filtre kahve.",
    story: [
      "Özenle toplanan kahve kirazları, küçük bir deliği olan tanklarda Lactobacillus ile 72 saat boyunca fermente edilerek sıradan tatların çok ötesinde, derinlikli bir profil kazanır.",
      "Damakta kan portakalının canlı, tatlı ve sulu narenciye karakteri; ara tatta kompleks kırmızı meyve katmanları; bitişte temiz ve kalıcı, tatlı bir iz.",
      "Geleneksel Endonezya kahvelerinin (wet hulled) aksine, Wildan Mustofa'nın 1.400 metre rakımlı Java Frinsa Estate tesisinde modern, titiz ve kontrollü bir işlemden geçerek fincan temizliğini en üst düzeye çıkarır.",
    ],
    image: img("frinsa3", "#d66e2f"),
    variants: variants("SKU-END-FR3", [
      [1749, 100, 325, 400],
      [1750, 200, 650, 800],
      [1748, 500, 1200, 1500],
      [1747, 1000, 2240, 2800],
    ]),
    grindOptions: GRIND_OPTIONS,
    brewGuides: {
      filter: v60({
        dose: 15,
        water: 236,
        temperature: 92,
        totalTime: 165,
        tip: "Önerimiz 1:15–1:16 oran, 90–93 °C su ve 2:15–3:00 süzülme. Aeropress / Kalita / Clever için 1:15, orta-kaba öğütme, 1:30–2:00.",
      }),
    },
    featured: true,
  },
  {
    id: "1199",
    slug: "endonezya-frinsa-estate-honey-saccharomyces-filtre",
    name: "Frinsa Honey",
    fullName: "Endonezya Frinsa Estate — Honey Saccharomyces",
    subtitle: "Endonezya · Weninggalih, Java",
    categories: ["single-origin"],
    headline: "Honey işlem, maya fermantasyonu",
    origin: { country: "Endonezya", region: "Weninggalih, Java", farm: "Java Frinsa Estate" },
    elevation: "1300 – 1600 m",
    process: "Honey + Saccharomyces (uzatılmış fermantasyon)",
    variety: [],
    harvest: "",
    roastLevel: "Açık",
    recommendedFor: "Filtre & Espresso",
    tastingNotes: [N.yabanMersini, N.bogurtlen, N.erik],
    bodyAcidity: "Orta-yüksek, sürükleyici gövde; dengeli, meyvemsi ama baskın olmayan asidite",
    description:
      "Endonezya Frinsa Estate Honey Saccharomyces kahve çekirdeği — yaban mersini, böğürtlen ve erik notalarıyla dengeli asidite ve zengin gövde.",
    story: [
      "Endonezya'nın Java bölgesinden, Weninggalih'in yüksek platolarında yetişen bu özel lot, sıradan kahvelerin ötesinde bir tat yolculuğu sunar. Honey işlemle başlayan yolculuk, Saccharomyces maya fermantasyonuyla tamamlanır.",
      "Damakta yoğun yaban mersini ve frenk üzümü tatlılığı, ara tatta şaraplık kırmızı meyve ve vişne, bitişte kalıcı bir erik izi. Espressoda kompakt ve yoğun, filtrede uzun bir tat sunumu; Aeropress ya da V60 ile dengeli bir meyve–tuğla tat dengesi.",
    ],
    image: img("endonezya-frinsa-estate-honey-saccharomyces-filtre", "#031433"),
    variants: variants("SKU-END-FRS", [
      [1202, 100, 305, 380],
      [1203, 200, 600, 750],
      [1201, 500, 1200, 1500],
      [1200, 1000, 2240, 2800],
    ]),
    grindOptions: GRIND_OPTIONS,
    brewGuides: {
      filter: v60({
        dose: 15,
        water: 255,
        temperature: 90,
        totalTime: 195,
        tip: "Önerimiz 1:16–1:18 oran, 88–92 °C su ve 2:00–3:30 süzülme. Aeropress / Kalita / Clever: 1:15, orta-kaba, 1:30–2:00.",
      }),
      espresso: espresso({ output: 38, time: 27, tip: "Espressoda kompakt ve yoğun bir meyve bombası." }),
    },
    featured: true,
  },
  {
    id: "1416",
    slug: "arjuna-endonezya",
    name: "Arjuna",
    fullName: "Arjuna Endonezya Wet Hulled",
    subtitle: "Endonezya · Garut, Batı Java",
    categories: ["single-origin", "espresso"],
    collection: "ruso-exotics",
    limited: true,
    headline: "Java'nın kremamsı gövdesi",
    origin: { country: "Endonezya", region: "Garut, Batı Java" },
    elevation: "1100 – 1400 m",
    process: "Wet Hulled (Giling Basah)",
    variety: ["Typica", "Ateng", "Catimor", "Sigararutang"],
    harvest: "Seçilmiş en olgun kirazlar",
    roastLevel: "Orta",
    recommendedFor: "Espresso & Filtre",
    tastingNotes: [N.karamel, N.esmerSeker, N.misketLimonu, N.kakao, N.baharat],
    bodyAcidity: "Tam gövde, kremamsı doku, düşük ve dengeli asidite",
    facts: [{ label: "Marka / Tedarik", value: "Ruso Exotics (Direct Trade)" }],
    description:
      "Arjuna Endonezya Wet Hulled kahve çekirdeği — karamel, esmer şeker, misket limonu, kakao ve baharat notalarıyla tam gövdeli, kremamsı ve düşük asiditeli.",
    story: [
      "Batı Java'nın Garut bölgesinde, 1.100–1.400 metrede yetişen Arjuna; Typica, Ateng, Catimor ve Sigararutang çeşitlerinin Endonezya'ya özgü Giling Basah (wet hulled) yöntemiyle işlenmesiyle doğar.",
      "Fincanda karamel ve esmer şeker tatlılığı, misket limonu ferahlığı ve kakao–baharat derinliği. Tam gövdeli, kremamsı bir doku ve düşük, dengeli bir asidite; espressoda olduğu kadar filtrede de güçlü.",
      "Bu özel seri, Ruso Exotics'in sınırlı stoklu (Limited Batch) butik seçkilerinden biridir.",
    ],
    image: img("arjuna-endonezya", "#eeaa5f"),
    variants: variants("SKU-END-ARJ", [
      [1419, 100, 272, 340, false],
      [1420, 200, 480, 600],
      [1418, 500, 1000, 1250],
    ]),
    grindOptions: GRIND_OPTIONS,
    brewGuides: {
      espresso: espresso({ output: 38, time: 28, tip: "Kremamsı gövde sütle harika: flat white için 1:2." }),
      filter: chemex({ tip: "Chemex'in kalın filtresi baharatı yumuşatır, karamel öne çıkar." }),
    },
    featured: true,
  },
  {
    id: "1205",
    slug: "manis-blend-espresso-filtre",
    name: "Manis",
    fullName: "Manis Blend",
    subtitle: "Endonezya × Etiyopya harmanı",
    categories: ["blends", "espresso"],
    headline: "Manis ile tatlı bir molaya hazır mısınız?",
    origin: { country: "Endonezya × Etiyopya", region: "Günlük harman" },
    elevation: "",
    process: "Harman",
    variety: [],
    harvest: "",
    roastLevel: "Orta",
    recommendedFor: "Filtre, V60 & AeroPress",
    tastingNotes: [N.cikolata, N.ormanMeyveleri, N.tarcin],
    sensory: { body: 3, acidity: 4, sweetness: 5 },
    bodyAcidity: "Yumuşak ve pürüzsüz gövde, nazik ve meyvemsi asidite, belirgin doğal tatlılık",
    description:
      "Manis Blend kahve çekirdeği — çikolata, orman meyveleri ve tarçın notalarıyla yumuşak, meyvemsi ve doğal tatlı günlük kahve; filtre ve espressoya uygun.",
    story: [
      "Adını Endonezce'de \"tatlı\" anlamına gelen kelimeden alan Manis, isminin hakkını sonuna kadar veriyor. Kahvenizde acılık yerine yumuşak, meyvemsi ve doğal şekerli tatlar arıyorsanız, Manis tam size göre.",
      "Özenli bir orta kavurmayla çekirdeğin içindeki doğal meyve şekerlerini dengeyle açığa çıkarıyoruz: zengin çikolata notalarına orman meyvelerinin canlılığı ve bitişte iç ısıtan bir tarçın dokunuşu eşlik ediyor.",
      "Pazar sabahı uzun uzun demlenen bir V60, ofiste hızlıca hazırlanan bir filtre kahve ya da ince öğütülmüş modern bir Türk kahvesi — her fincanda yormayan, keyifli bir deneyim.",
    ],
    image: img("manis-blend-espresso-filtre", "#37afdb", "box", 1.1),
    variants: variants("SKU-ETH-SDM", [
      [1208, 100, 200, 250],
      [1209, 250, 360, 450],
      [1207, 500, 650, 800],
      [1206, 1000, 1200, 1500],
    ]),
    grindOptions: GRIND_OPTIONS,
    brewGuides: {
      filter: v60({ tip: "Meyvemsi ve tatlı notalar için V60, AeroPress ya da filtre kahve makinesi." }),
      espresso: espresso({ tip: "Sade espressoda çikolatalı, sütle tarçınlı bir kapanış." }),
    },
    featured: true,
  },
  {
    id: "1524",
    slug: "pagi",
    name: "Pagi",
    fullName: "Pagi Blend",
    subtitle: "Etiyopya × Endonezya harmanı",
    categories: ["blends", "espresso"],
    headline: "Pagi ile sabahlarınıza lezzet katın",
    origin: { country: "Etiyopya × Endonezya", region: "Günlük harman" },
    elevation: "",
    process: "Harman",
    variety: [],
    harvest: "",
    roastLevel: "Orta",
    recommendedFor: "Filtre & Sütlü içecekler",
    tastingNotes: [N.karamel, N.badem, N.cikolata],
    sensory: { body: 3, acidity: 3, sweetness: 4 },
    bodyAcidity: "Dengeli ve yuvarlak gövde, yumuşak ve nazik asidite, belirgin doğal tatlılık",
    description:
      "Pagi Blend kahve çekirdeği — karamel, badem ve çikolata notalarıyla dengeli, her gün içilecek bir harman; filtre kahve ve latte, cappuccino, flat white için ideal.",
    story: [
      "Adını Endonezce'de \"sabah\" anlamına gelen kelimeden alan Pagi, güne mükemmel bir başlangıç yapmanız için tasarlandı. Etiyopya'nın parlak ve canlı karakterini Endonezya'nın zengin dokusuyla buluşturan bu özel harman, sabah mahmurluğunu keyifli bir uyanışa çeviriyor.",
      "Orta kavurmayla fincanda tam bir denge: ilk yudumda tatlı karamel ve kavrulmuş badem, bitişte doyurucu ve yumuşak bir çikolata. Gün boyu bıkmadan içebileceğiniz, yormayan bir \"her gün\" kahvesi.",
    ],
    image: img("pagi", "#f2b600", "pouch", 0.981),
    variants: variants("", [
      [1527, 100, 200],
      [1528, 250, 350],
      [1526, 500, 600],
      [1525, 1000, 1200],
    ]),
    grindOptions: GRIND_OPTIONS,
    brewGuides: {
      filter: v60({ tip: "Filtre makinesi, V60 ya da French Press ile dengeli bir sabah fincanı." }),
      espresso: espresso({ output: 36, time: 27, tip: "Latte, cappuccino ve flat white için güçlü bir temel." }),
    },
  },
  {
    id: "1531",
    slug: "tanah",
    name: "Tanah",
    fullName: "Tanah Blend",
    subtitle: "Etiyopya × Endonezya harmanı",
    categories: ["blends", "espresso"],
    headline: "Kahvenin en güçlü hâliyle tanışın",
    origin: { country: "Etiyopya × Endonezya", region: "Günlük harman" },
    elevation: "",
    process: "Harman",
    variety: [],
    harvest: "",
    roastLevel: "Orta-Koyu",
    recommendedFor: "Espresso, Moka Pot & Türk Kahvesi",
    tastingNotes: [N.bitterCikolata, N.kuruyemis, N.baharat],
    sensory: { body: 5, acidity: 2, sweetness: 4 },
    bodyAcidity: "Tam gövdeli ve yoğun; düşük, rahatsız etmeyen asidite",
    description:
      "Tanah Blend kahve çekirdeği — bitter çikolata, kavrulmuş kuruyemiş ve baharat notalarıyla tam gövdeli, düşük asiditeli; espresso, moka pot ve Türk kahvesi için.",
    story: [
      "Adını Endonezce'de \"toprak\" anlamına gelen kelimeden alan Tanah, kahveden yoğunluk, güç ve gövde bekleyenler için harmanlandı. Etiyopya ve Endonezya'nın en karakteristik çekirdekleri, kahvenin o derin ve topraksı doğasını ortaya çıkarmak için bir araya geldi.",
      "Orta-koyu kavurma profilimiz zengin aromaları açığa çıkarırken asiditeyi en aza indirir: yoğun bitter çikolata ve kavrulmuş kuruyemiş, bitişte damakta sıcak bir baharat esintisi.",
      "Sütün içinde kaybolmayan güçlü yapısıyla latte ve cortado için harika; sert bir filtre kahve sevenler için de French Press.",
    ],
    image: img("tanah", "#4f4441", "pouch", 0.988),
    variants: variants("", [
      [1534, 100, 200],
      [1535, 250, 350],
      [1533, 500, 600],
      [1532, 1000, 1200],
    ]),
    grindOptions: GRIND_OPTIONS,
    brewGuides: {
      espresso: espresso({ output: 36, time: 26, temperature: 92, tip: "Orta-koyu kavrum: acılığı önlemek için 92 °C." }),
      filter: frenchPress({ tip: "Sert ve gövdeli bir filtre için French Press." }),
    },
    featured: true,
  },
  {
    id: "1753",
    slug: "kafeinsizmeksika",
    name: "Decaf Meksika",
    fullName: "Kafeinsiz Meksika — Swiss Water Decaf",
    subtitle: "Meksika · Altura, Chiapas",
    categories: ["single-origin", "espresso"],
    headline: "Kimyasalsız, %99,9 kafeinsiz",
    origin: { country: "Meksika", region: "Altura, Chiapas" },
    elevation: "1300 m",
    process: "Swiss Water (doğal su ile kafeinsizleştirme)",
    variety: ["%100 Arabica"],
    harvest: "",
    roastLevel: "Orta",
    recommendedFor: "Espresso & Filtre",
    tastingNotes: [N.sutluCikolata, N.findik],
    bodyAcidity: "Orta gövde, dengeli ve yormayan asidite, pürüzsüz içim",
    description:
      "Kafeinsiz Meksika Swiss Water Decaf kahve çekirdeği — kimyasal kullanılmadan %99,9 kafeinsizleştirilmiş; sütlü çikolata ve fındık notalarıyla pürüzsüz ve tatlı.",
    story: [
      "Herhangi bir kimyasal kullanılmadan, yalnızca su, ozmoz ve çözünürlük prensipleriyle %99,9 oranında kafeinsizleştirilen Swiss Water işlemi; dağ suyu kahvenin orijinal tat ve aromasını korur.",
      "Çekirdeklerin tat ve yağ asitlerini korumak için City (orta) seviyede kavuruyoruz — asidite ve aromanın en dengeli noktası. Damakta sütlü çikolatanın tatlı, pürüzsüz ve ipeksi dokunuşu.",
      "Tüm çekirdeklerimiz haftalık olarak kavrulur; paketteki üretim tarihi, kahvenizin kavrulduğu gündür. En iyi lezzet için 1 ay içinde tüketmenizi öneririz.",
    ],
    image: img("kafeinsizmeksika", "#311e17", "box", 1.084),
    variants: variants("SKU-END-ARJ-1", [
      [1755, 100, 275, 340],
      [1756, 200, 485, 600],
      [1754, 500, 1000, 1250],
    ]),
    grindOptions: GRIND_OPTIONS,
    brewGuides: {
      espresso: espresso({ tip: "Akşam espressosu: sütle sütlü çikolata gibi." }),
      filter: v60(),
    },
    featured: true,
  },
  {
    id: "1299",
    slug: "watermelon-colombia",
    name: "Watermelon",
    fullName: "Jairo Arcila Watermelon Colombia — Washed",
    subtitle: "Kolombiya · Armenia, Quindío",
    categories: ["single-origin"],
    headline: "Sıradışı bir yaz rüzgârı",
    origin: { country: "Kolombiya", region: "Armenia, Quindío", producer: "Jairo Arcila", farm: "Santa Monica" },
    elevation: "1450 – 1500 m",
    process: "Washed + Watermelon (48 saat anaerobik fermantasyon + karpuz ilavesi)",
    variety: ["Castillo"],
    harvest: "Seçilmiş en olgun kirazlar",
    roastLevel: "Açık",
    recommendedFor: "Filtre",
    tastingNotes: [N.karpuz, N.balKavunu, N.nane, N.misketLimonu, N.cikolata],
    bodyAcidity: "Canlı profil, pürüzsüz orta gövde, parlak asidite",
    facts: [{ label: "Toprak yapısı", value: "Volkanik kül" }],
    description:
      "Jairo Arcila Watermelon Colombia kahve çekirdeği — 48 saat anaerobik fermantasyon ve karpuz ilavesi; karpuz, bal kavunu, nane ve misket limonu notaları.",
    story: [
      "Kolombiya'nın Armenia, Quindío bölgesinde, 1450–1500 metre yükseklikteki volkanik topraklarda yetişen bu kahve, kahve dünyasının sınırlarını zorlayan deneysel bir sürecin ürünü. Ünlü üretici Jairo Arcila'nın Santa Monica çiftliğinde yetiştirdiği Castillo çekirdekleri.",
      "Yüzdürme tanklarında ayıklanan kirazlar La Pradera işleme merkezinde 48 saatlik kuru anaerobik fermantasyona alınır; tanklara eklenen gerçek karpuz, çekirdeklere o eşsiz sulu tatlılığı kazandırır. Ardından yıkanır ve elbas yataklarında %9,5–11 nem oranına ulaşana kadar yaklaşık 10 gün kurutulur.",
      "Fincanda baskın karpuz ve bal kavunu, ferahlatıcı bir nane dokunuşu ve misket limonu asiditesi; bitişte Castillo'ya özgü yumuşak bir çikolata.",
    ],
    image: img("watermelon-colombia", "#780618"),
    variants: soldOut(
      variants("SKU-CLM-WTM", [
        [1302, 100, 600, 750],
        [1303, 200, 1000, 1250],
        [1301, 500, 2200, 2750],
        [1300, 1000, 4500],
      ]),
    ),
    grindOptions: GRIND_OPTIONS,
    brewGuides: { filter: kalita({ temperature: 92 }) },
  },
  {
    id: "1429",
    slug: "papandayan-endonezya",
    name: "Papandayan",
    fullName: "Papandayan Endonezya Natural",
    subtitle: "Endonezya · Garut, Batı Java",
    categories: ["single-origin"],
    collection: "ruso-exotics",
    limited: true,
    headline: "Java'nın vahşi ve zarif yüzü",
    origin: { country: "Endonezya", region: "Papandayan, Garut, Batı Java" },
    elevation: "1100 – 1400 m",
    process: "Natural (Doğal)",
    variety: ["Typica", "Ateng", "Catimor", "Sigararutang"],
    harvest: "El ile seçilmiş en olgun kirazlar",
    roastLevel: "Açık-Orta",
    recommendedFor: "Filtre",
    tastingNotes: [N.ciceksi, N.ahududu, N.erik],
    bodyAcidity: "Orta-yüksek gövde, canlı ve meyvemsi asidite",
    facts: [{ label: "Marka / Tedarik", value: "Ruso Exotics (Direct Trade)" }],
    description:
      "Papandayan Endonezya Natural kahve çekirdeği — Batı Java'nın Papandayan yanardağı eteklerinden; çiçeksi, ahududu ve erik notalarıyla mikro lot.",
    story: [
      "Batı Java'nın en ikonik zirvelerinden Papandayan Yanardağı'nın eteklerinden, Garut'un bereketli topraklarından gelen bu kahve; Natural işlemin yoğun meyvemsi karakterini Typica ve Sigararutang gibi seçkin çeşitlerin zarafetiyle birleştiriyor.",
      "İlk yudumda damakta patlayan canlı ahududu ve tatlı erik, kahve soğudukça yerini zarif çiçeksi bir bitişe bırakıyor. Kirazlar kabuklarıyla birlikte güneşte kurutulur; meyvenin tüm şekeri çekirdeğin kalbine hapsolur.",
      "Ruso Exotics tarafından Endonezya'daki tarlalardan bizzat seçilen, sınırlı hasat edilen bir mikro lot.",
    ],
    image: img("papandayan-endonezya", "#7f262b"),
    variants: soldOut(
      variants("SKU-END-PPD", [
        [1432, 100, 400, 450],
        [1433, 200, 750, 950],
        [1431, 500, 1500, 1800],
      ]),
    ),
    grindOptions: GRIND_OPTIONS,
    brewGuides: { filter: v60({ temperature: 92 }) },
  },
  {
    id: "shantawene",
    slug: "ethiopia-shantawene",
    name: "Shantawene",
    fullName: "Shantawene Etiyopya Natural",
    subtitle: "Etiyopya · Sidama",
    categories: ["single-origin"],
    origin: { country: "Etiyopya", region: "Shantawene, Sidama" },
    elevation: "",
    process: "Natural (Doğal)",
    variety: ["Etiyopya yerel çeşitleri (Heirloom)"],
    harvest: "",
    roastLevel: "Açık",
    recommendedFor: "Filtre",
    tastingNotes: [N.bergamot, N.portakalKabugu, N.kakaoNibs],
    description:
      "Shantawene Etiyopya Natural kahve çekirdeği — bergamot, portakal kabuğu ve kakao nibs notaları. Yeni hasat geldiğinde tekrar stokta.",
    story: [
      "Sidama'nın yüksek köylerinden Shantawene; doğal yöntemle kurutulan kirazların meyvemsi derinliğini Etiyopya'nın çiçeksi zarafetiyle buluşturuyor.",
      "Fincanda bergamotun aromatik parlaklığı, portakal kabuğunun canlı narenciyesi ve kapanışta kakao nibs. Yeni hasat geldiğinde haber vermemiz için aşağıdan kaydolabilirsiniz.",
    ],
    image: img("ethiopia-shantawene", "#ec9445"),
    variants: [],
    grindOptions: GRIND_OPTIONS,
    brewGuides: { filter: v60({ temperature: 94 }) },
  },
];
